services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pharmaline\PhlAbc\:
    resource: '../src/*'
    exclude: '../src/Domain/Model/*'

  Pharmaline\PhlAbc\Utility\ErrorHandlerUtility:
    public: true

  Pharmaline\PhlAbc\Security\Voter\VoterInterface:
    public: true

  Pharmaline\PhlAbc\Security\SecurityManager:
    public: true
    arguments:
      $registry: '@Pharmaline\PhlAbc\Security\Service\VoterRegistry'
      $defaultStrategy: '@Pharmaline\PhlAbc\Security\Strategy\UnanimousStrategy'

